[package]
name = "apple-push"
description = "Apple Push Notification Service (apns) client library"
version = "0.2.0"
authors = ["Jasper Bryant-Greene <jbg@rf.net.nz>"]
license = "MIT/Apache-2.0"
readme = "README.md"
categories = ["network-programming"]
repository = "https://github.com/jbg/apns2-rust"

[dependencies]
failure = "0.1.1"
futures-preview = { version = "0.3.0-alpha.15", features = ["compat"] }
hyper = "0.12"
jsonwebtoken = { git = "https://github.com/jbg/jsonwebtoken" }
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
uuid = { version = "0.6.0", features = ["serde", "v4"] }

[dev-dependencies]
base64 = "0.9"
hyper-tls = "0.3"
tokio = "0.1"
